# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 943adaf0acc20ba6c7245175c5b22271431e1c1d48bd2c022008a16ed627ffe30f48dddfa9efadf420a7ca0f05e8642efec9241a06c640dc699834ecdbef6c24

test:
  secret_key_base: 6e1d4324483258fc9ab9cbcc75a6051e60dec0b6f50443f9c41ab833cb15c6cb14ade8428abe1f5a2619966672e10d3801ed20b6bd11bfce7cc0251c373fdc95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
